# app
app:
  host: 0.0.0.0
  port: 8000
  secret: secret

# postgres
postgres:
  user: postgres
  password: postgres
  database: mydbname
  port: 5432
  host: postgres

redis:
  port: 6380
  host: redis
